name: "GH-200 Action"
description: "GH-200: GitHub Actions"
inputs:
  base: # id of input
    description: "Base URL"
    required: true
    default: "https://docs.github.com/en/actions/get-started/understand-github-actions"
outputs:
  time: # id of output
    description: "Shows URL"
runs:
  using: "node16"
  main: "dist/index.js"
branding:
  icon: "globe"
  color: "blue"
